#!/usr/bin/env ruby

require "nrepl_server"

EventMachine.run do
  # hit Control + C to stop
  Signal.trap("INT")  { EventMachine.stop }
  Signal.trap("TERM") { EventMachine.stop }

  EventMachine.start_server("127.0.0.1", 7889, NReplServer::Server)
end
